DECLARE @CUSTID VARCHAR(10)
SET @CUSTID = 'AAA0001001'
SELECT 
	CUSTID,
	PRODUCTID,
	CONVERT (nvarchar(100), PRODCNAME) PRODCNAME,
	SUM (QUANTITY - RETURNQTY) AS LEFTQTY,
	(
		SELECT
			CEILING(AVG(RETURNQTY))
		FROM
			STKBORROWSUB
		WHERE
			(FLAG = '4')
		AND (CUSTID = @CUSTID)
		AND (
			SUBSTRING (PRODUCTID, 1, 1) <> 'E'
		)
	) AS AVG_RETURN
FROM
	STKBORROWSUB
WHERE
	(CUSTID = @CUSTID)
AND (FLAG = '3')
AND (QUANTITY <> RETURNQTY)
AND (
	SUBSTRING (PRODUCTID, 1, 1) <> 'E'
)
GROUP BY
	CUSTID,
	PRODUCTID,
	PRODCNAME
ORDER BY
	PRODUCTID;
